# Generated by Django 4.1.4 on 2023-01-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="coverage_type",
            field=models.CharField(
                choices=[("basic", "basic"), ("premium", "premium")],
                default="basic",
                max_length=20,
            ),
        ),
    ]
