# Generated by Django 4.1.4 on 2023-01-05 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinformation_coverage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
