# Generated by Django 4.1.4 on 2023-01-04 19:48

from django.db import migrations


def create_states(apps, schema_editor):
    State = apps.get_model("states", "State")
    existing_states = [state.state for state in State.objects.all()]

    states_to_create = [
        {"state": "CA", "flood_cost_percentage": 0.02, "monthly_tax": 0.01},
        {"state": "TX", "flood_cost_percentage": 0.5, "monthly_tax": 0.005},
        {"state": "NY", "flood_cost_percentage": 0.1, "monthly_tax": 0.02},
    ]

    for data in states_to_create:
        if data["state"] not in existing_states:
            State.objects.create(**data)


def reverse_states(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_states, reverse_states),
    ]
