# Generated by Django 4.1.4 on 2023-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubmittedUrls",
            fields=[
                ("submit_datetime_utc", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(primary_key=True, serialize=False)),
                ("is_processing", models.BooleanField(default=False)),
                ("processing_start_datetime_utc", models.DateTimeField(null=True)),
                ("is_complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Words",
            fields=[
                (
                    "word",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("count", models.BigIntegerField()),
            ],
        ),
    ]
