# Generated by Django 4.1.4 on 2023-01-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("coverage_type", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=2)),
                ("has_pet", models.BooleanField()),
                ("include_flood_coverage", models.BooleanField()),
                ("monthly_subtotal", models.FloatField()),
                ("monthly_taxes", models.FloatField()),
                ("monthly_total", models.FloatField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "unique_together": {
                    (
                        "user_id",
                        "coverage_type",
                        "state",
                        "has_pet",
                        "include_flood_coverage",
                    )
                },
            },
        ),
    ]
